Smalltalk current createPackage: 'Flow-Errors' properties: #{}!
Error subclass: #FlowError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #ModelUpdateError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #ModelReadError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #ModelDeleteError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #ModelCreateError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #AjaxError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #ModelRefeshError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #MissingInstanceVariableReifier
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #MissingItemsError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

FlowError subclass: #GettingItemsError
	instanceVariableNames: ''
	category: 'Flow-Errors'!

